In [19]:
import numpy as np
import pandas as pd

books = pd.read_csv("/Users/benjamingoldblatt/webscraper/goodreads.csv")
ranked_books = books.sort_values(by=["rating"], ascending=False)

print(ranked_books)

               genre                                              title  \
616           Memoir                               Know My Name (ebook)   
165       Children's  Harry Potter and the Deathly Hallows (Harry Po...   
475   Graphic Novels         Heartstopper: Volume Two (Heartstopper #2)   
435          Fantasy      The Way of Kings (The Stormlight Archive, #1)   
240        Christian     An Echo in the Darkness (Mark of the Lion, #2)   
...              ...                                                ...   
750           Poetry                                Beowulf (Paperback)   
1059          Travel            Bill Bryson's African Diary (Hardcover)   
603           Horror                  The Turn of the Screw (Paperback)   
262         Classics                     The Scarlet Letter (Paperback)   
1097     More genres                    The Heart Goes Last (Hardcover)   

                   author  rating  reviews  year  
616         Chanel Miller    4.72   103482  2019

In [20]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split 

y = books['genre'].values
X = books.drop(['genre','title','author'], axis=1).values
print(y)
print(X)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4, random_state=3, stratify=y)
print ("X_train: ", X_train)
print ("y_train: ", y_train)
print("X_test: ", X_test)
print ("y_test: ", y_test)
# Create a k-NN classifier with 7 neighbors: knn
knn = KNeighborsClassifier(n_neighbors=10)

# Fit the classifier to the training data
knn.fit(X_train, y_train)

# Print the accuracy
print(knn.score(X_test, y_test))


['Art' 'Art' 'Art' ... 'More genres' 'More genres' 'More genres']
[[3.89000e+00 2.93165e+05 1.97200e+03]
 [3.94000e+00 3.45375e+05 1.95000e+03]
 [3.87000e+00 3.16283e+05 1.97900e+03]
 ...
 [3.93000e+00 3.95073e+05 2.01700e+03]
 [4.03000e+00 3.95900e+04 1.97600e+03]
 [3.77000e+00 1.52285e+05 2.01500e+03]]
X_train:  [[3.94000e+00 1.33678e+05 2.01100e+03]
 [4.08000e+00 2.56057e+05 2.00000e+03]
 [3.80000e+00 3.32460e+04 1.96200e+03]
 ...
 [4.17000e+00 6.05230e+04 1.96100e+03]
 [3.46000e+00 9.03000e+03 2.00200e+03]
 [4.22000e+00 6.88031e+05 2.00700e+03]]
y_train:  ['Psychology' 'Memoir' 'Art' 'Art' 'Art' 'Music' 'Ebooks' 'Classics'
 'Biography' 'Comics' 'Sports' 'Art' 'Thriller' 'Horror' 'Business'
 'Comics' 'Thriller' 'Classics' 'Self Help' 'Horror' 'Romance' 'Business'
 'Ebooks' 'Memoir' "Children's" 'History' 'Fantasy' 'Art'
 'Historical Fiction' 'Travel' 'Romance' 'Business' 'Sports' 'Fiction'
 'History' "Children's" 'Business' 'Science Fiction' 'Memoir' 'Romance'
 'Memoir' 'Graphic Nov